config/routes.rb
Rails.application.routes.draw do
  resources :teacher_clocks, except: :show
  root 'teacher_clocks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/teacher_clock.rb
class TeacherClock < ApplicationRecord
  before_create :generate_teacher_logged_time
  before_validation :store_teacher_logged_time_before_initial_validation

  validates :teacher_name, presence: true, allow_nil: false
  validates :teacher_clocked_in, inclusion: [true, false], allow_nil: false
  validates :teacher_logged_time, presence: true, allow_nil: false

  private
    def generate_teacher_logged_time
      self.teacher_logged_time = DateTime.now
    end

    def store_teacher_logged_time_before_initial_validation
      if self.id == nil
        generate_teacher_logged_time
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/teacher_clocks_controller.rb
class TeacherClocksController < ApplicationController
  #before_action :set_teacher_clock, only: [:show, :edit, :update, :destroy]

  def index
    @teacher_clocks = TeacherClock.order('teacher_logged_time DESC').all
  end

  def show
    @teacher_clock = TeacherClock.find(params[:id])
  end

  def new
    #@teacher_clock = TeacherClock.new
  end

  def edit
    @teacher_clock = TeacherClock.find(params[:id])
  end

  def create
    @teacher_clock = TeacherClock.new(teacher_clock_params)
    
    if @teacher_clock.save
      redirect_to teacher_clocks_path
    else
      redirect_to new_teacher_clock_path
    end
  end

  def update
    @teacher_clock = TeacherClock.find(params[:id])

    if @teacher_clock.update(teacher_clock_params)
      redirect_to teacher_clocks_path
    else
      redirect_to edit_teacher_clock_path
    end
  end

  # DELETE /teacher_clocks/1
  # DELETE /teacher_clocks/1.json
  def destroy
    @teacher_clock = TeacherClock.find(params[:id])
    @teacher_clock.destroy
    redirect_to teacher_clocks_path
  end

  private
    def teacher_clock_params
      params.require(:teacher_clock).permit(:teacher_name, :teacher_logged_time, :teacher_clocked_in)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/teacher_clocks_helper.rb
module TeacherClocksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <title>Teacher Clock In-Out</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>
    <!-- Option 1: jQuery and Bootstrap Bundle (includes Popper) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
  </body>
</html>

app/views/teacher_clocks/_edit_form.html.erb
<%= form_with model: @teacher_clock, local: true, class: 'form' do |form| %>
  <div class="field form-group">
    <span class="badge badge-primary">Teacher's Name</span>
    <%= form.text_field :teacher_name, class: "form-control" %>
  </div>
  <div class="field form-group">
      <span class="badge badge-primary">Teacher's Logged Time</span>
      <%= form.datetime_field :teacher_logged_time, class: "form-control" %>
  </div>
  <div class="form-group form-check">
    <%= form.check_box :teacher_clocked_in, class: "form-check-input" %>
    <%= form.label :teacher_clocked_in, "Check Box (ONLY to Clock In)", class: "form-check-label" %>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit "Edit Clock In-Out Event", class: "btn btn-secondary" %>
  </div>
<% end %>

app/views/teacher_clocks/_new_form.html.erb
<%= form_with scope: :teacher_clock, url: teacher_clocks_path, local: true, class: 'form' do |form| %>
  <div class="field form-group">
    <%= form.text_field :teacher_name, class: "form-control", placeholder: "Teacher's Name" %>
  </div>
  <div class="form-group form-check">
    <%= form.check_box :teacher_clocked_in, class: "form-check-input" %>
    <%= form.label :teacher_clocked_in, "Check Box (ONLY to Clock In)", class: "form-check-label" %>
  </div>
  <br/>
  <div class="actions">
    <%= form.submit "Create Clock In-Out Event", class: "btn btn-secondary" %>
  </div>
<% end %>
  

app/views/teacher_clocks/edit.html.erb
<h1>Edit Clock In-Out Event</h1>
<br/>
<%= render 'edit_form' %>

app/views/teacher_clocks/index.html.erb
<div class="row">
  <div class="col text-center">
    <%= link_to "Click to Create New Clock In-Out Event", new_teacher_clock_path, class: "btn btn-primary text-white" %>
  </div>
</div>
<br/>
<table class="table table-striped">
  <thead class="thead-dark">
    <tr>
      <th scope="col">Teacher</th>
      <th scope="col">Logged Time</th>
      <th scope="col">Status</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @teacher_clocks.each do |teacher_clock| %>
      <% @teacher_clock = teacher_clock %>
      <tr>
        <th scope="row"><%= @teacher_clock.teacher_name %></th>
        <td><%= @teacher_clock.teacher_logged_time.strftime('%B %e, %Y - %l:%M %p') %></td>
        <td>
          <span class="badge badge-pill <%= @teacher_clock.teacher_clocked_in ? 'badge-success' : 'badge-danger' %>">
            <%= @teacher_clock.teacher_clocked_in ? 'Clocked In' : 'Clocked Out' %>
          </span>
        </td>
        <td>
          <%= link_to "Edit", edit_teacher_clock_path(@teacher_clock), class: "btn btn-sm btn-warning" %>
          <%= link_to "Delete", teacher_clock_path(@teacher_clock), method: :delete, class: "btn btn-sm btn-danger" %>
        </td>
      </tr>
      <% end %>
  </tbody>
</table>

app/views/teacher_clocks/new.html.erb
<h1>New Clock In-Out Event</h1>
<br/>
<%= render 'new_form' %>
<br/>